"""
NOCOPO — Gate B Validation Suite Runner
=======================================
Phase 6: Core Model Implementation & Validation
Project: Nigeria Public Procurement Intelligence

Purpose
-------
Run the full validation suite and write the Gate B results log.

  Stage 1  Raw -> staging: python/ingest/02_reconcile_staging.py
           (independent traversal of the source JSON).
  Stage 2  Every sql/03_data_quality/*.sql file, in filename order.
           Each file returns rows of:
             check_id, check_group, check_name, severity, expected, actual, passed
           severity GATE must pass; INFO records a measurement.

The checks themselves live in SQL. This script only executes them and
formats the results.

Usage
-----
    python python/validation/04_run_validation_suite.py

Output
------
    docs/phase6_core_model/phase6_validation_results.md
    Exit code 1 if any GATE check fails.
"""

import glob
import os
import subprocess
import sys
from datetime import datetime

import psycopg

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SUITE_DIR = os.path.join(ROOT, "sql", "03_data_quality")
STAGE1 = os.path.join(ROOT, "python", "ingest", "02_reconcile_staging.py")
OUTPUT = os.path.join(ROOT, "docs", "phase6_core_model", "phase6_validation_results.md")


def main():
    # Stage 1 — raw -> staging (independent of SQL)
    stage1 = subprocess.run([sys.executable, STAGE1], capture_output=True, text=True)
    stage1_summary = (stage1.stdout.strip().splitlines() or ["(no output)"])[-1].split(" Report:")[0]
    stage1_ok = stage1.returncode == 0

    # Stage 2 — SQL suite
    conninfo = dict(
        host=os.environ.get("PGHOST", "localhost"),
        port=os.environ.get("PGPORT", "5433"),
        user=os.environ.get("PGUSER", "postgres"),
        dbname=os.environ.get("PGDATABASE", "nocopo_db"),
    )
    files = sorted(glob.glob(os.path.join(SUITE_DIR, "*.sql")))
    results = []
    with psycopg.connect(**conninfo) as conn, conn.cursor() as cur:
        server = cur.execute("SHOW server_version").fetchone()[0]
        for path in files:
            with open(path, encoding="utf-8") as fh:
                cur.execute(fh.read())
            for row in cur.fetchall():
                results.append((os.path.basename(path),) + row)

    gate = [r for r in results if r[4] == "GATE"]
    gate_failed = [r for r in gate if r[7] is not True]
    info = [r for r in results if r[4] == "INFO"]
    passed = stage1_ok and not gate_failed

    fmt = lambda v: "" if v is None else (f"{int(v):,}" if v.lstrip("-").isdigit() else v)
    out = [
        "# Phase 6 — Gate B Validation Results",
        "",
        "> **Runner:** `python/validation/04_run_validation_suite.py`  ",
        f"> **Run date:** {datetime.now():%Y-%m-%d %H:%M:%S}  ",
        f"> **Database:** `{conninfo['dbname']}` on {conninfo['host']}:{conninfo['port']} (PostgreSQL {server})  ",
        f"> **Gate B result:** {'**PASSED**' if passed else '**FAILED**'}. "
        f"Stage 1 {'passed' if stage1_ok else 'FAILED'}; "
        f"{len(gate) - len(gate_failed)} / {len(gate)} GATE checks passed; {len(info)} INFO measurements.",
        "",
        "Interpretation and decisions: `docs/phase6_core_model/phase6_core_model.md`.",
        "",
        "## Stage 1 — Raw → staging (independent JSON traversal)",
        "",
        f"`python/ingest/02_reconcile_staging.py`: {stage1_summary} "
        f"({'✓' if stage1_ok else '✗ FAIL'}). Detail: `docs/phase5_staging/phase5_staging_results.md`.",
        "",
        "## Stage 2 — SQL validation suite (`sql/03_data_quality/`)",
    ]
    group = None
    for f, cid, grp, name, sev, exp, act, ok in results:
        if grp != group:
            group = grp
            out += ["", f"### {grp} — `{f}`", "", "| ID | Check | Severity | Expected | Actual | Result |",
                    "|---|---|---|---|---|---|"]
        status = "✓" if ok is True else ("✗ FAIL" if sev == "GATE" else "info")
        out.append(f"| {cid} | {name} | {sev} | {fmt(exp)} | {fmt(act)} | {status} |")
    out += ["", "---", "", "*Generated by `python/validation/04_run_validation_suite.py`. Raw dataset not modified.*", ""]

    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))
    print(f"Stage 1: {stage1_summary}")
    print(f"Stage 2: {len(gate) - len(gate_failed)}/{len(gate)} GATE passed, {len(info)} INFO. Report: {OUTPUT}")
    for r in gate_failed:
        print(f"  FAILED {r[1]} {r[3]}: expected {r[5]}, actual {r[6]}")
    sys.exit(0 if passed else 1)


if __name__ == "__main__":
    main()
